version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: laravel_app
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: reunioes
      DB_USERNAME: root
      DB_PASSWORD: secret

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: reunioes
    volumes:
      - dbdata:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
    container_name: react_app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    command: ["npm", "start"]

volumes:
  dbdata:
